# Generated by Django 6.0.6 on 2026-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_chat_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='gcp_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
