# Generated by Django 6.0.6 on 2026-07-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_mcpserver_usermcpconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermcpconnection',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
